name: Pull request to build token lib and app artifacts
on:
  pull_request:
    branches:
      - '**'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: |
          git status --short
        shell: bash
      - name: Commit token generated styles
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
            message: 'chore: build token lib'
      - name: Upload lib artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: lib_artifact
          path: './dist/token-lib'
          retention-days: 1
