name: Pull request to build token lib and app artifacts
on:
  pull_request:
    branches:
      - '**'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  # Checkout the PR branch
          fetch-depth: 0  # Fetch all history
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Build tokens
        run: npm run build

      - name: Check for changes
        id: git-check
        run: |
          echo ".github{}" >> token-lib/css/variables.css
          echo "Branch=$(git branch --show-current)"
          git add .
          git status --porcelain

      - name: Commit changes if any
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Chore: Update CSS variables'

      - name: Upload lib artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: lib_artifact
          path: './dist/token-lib'
          retention-days: 1
