name: Pull request to build token lib and app artifacts
on:
  pull_request:
    branches:
      - '**'

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Upload lib artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: lib_artifact
          path: './dist/token-lib'
          retention-days: 1
